quarkus.application.name=pnc-deliverables-analyzer

quarkus.http.idle-timeout=1H
quarkus.http.cors.enabled=false
quarkus.http.cors.origins=/.*/

quarkus.http.enable-compression=true
quarkus.http.enable-decompression=true

quarkus.shutdown.timeout=30

# OIDC
%dev.quarkus.keycloak.devservices.enabled=false
%test.quarkus.keycloak.devservices.enabled=false
# TODO Tomas: Keycloak setup?

# LDAP
# required for LDAP1: build-time property
quarkus.http.auth.basic=true

quarkus.security.ldap.enabled=true
quarkus.security.ldap.cache.enabled=true
quarkus.security.ldap.cache.max-age=5m
quarkus.security.ldap.dir-context.url=ldaps://ldap-server.com
quarkus.security.ldap.identity-mapping.search-base-dn=ou=company.com

%test.quarkus.http.auth.basic=false
%test.quarkus.security.ldap.enabled=false

# Packaging
quarkus.package.output-name=deliverables-analyzer
quarkus.package.jar.enabled=true
quarkus.package.jar.type=fast-jar

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.jboss.pnc".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e mdc:[%X]%n
quarkus.log.handler.kafka.enabled=true
quarkus.log.handler.kafka.broker-list=kafka.example.com:443
quarkus.log.handler.kafka.topic=kafka-topic
quarkus.log.handler.kafka.security-protocol=SSL
quarkus.log.handler.kafka.ssl-truststore-location=/mnt/kafka-client-truststore.jks
quarkus.log.handler.kafka.ssl-truststore-password=none
quarkus.log.handler.kafka.filter-logger-name-pattern=org.jboss.pnc.*
quarkus.log.handler.kafka.level=INFO
%dev.quarkus.log.handler.kafka.enabled=false
%test.quarkus.log.handler.kafka.enabled=false

%dev.quarkus.log.console.json.enabled=false
%test.quarkus.log.console.json.enabled=false

# Infinispan. Options: EMBEDDED or REMOTE
# TODO Tomas: Only allow Remote (per Quarkus default)?
infinispan.mode=REMOTE
quarkus.infinispan-client.hosts=localhost:11222
quarkus.infinispan-client.username=admin
quarkus.infinispan-client.password=password

# Infinispan Caches
quarkus.infinispan-client.cache.cancel-events.configuration-resource=/cache/cancel-events-cache.xml
quarkus.infinispan-client.cache.file-SHA256.configuration-resource=/cache/file-SHA256-cache.xml

# PNC Rest Client
quarkus.rest-client.pnc-api.url=${analyzer.pnc-url}
quarkus.rest-client.pnc-api.read-timeout=30000

# Config
%test.callback.auth.enabled=false
%dev.callback.auth.enabled=false
#analyzer.pnc-url=https://orch-main-devel.pnc.engineering.redhat.com
analyzer.pnc-url=https://orch.pnc.engineering.redhat.com
analyzer.koji-url=https://brewhub.engineering.redhat.com/brewhub

# TODO Tomas: Add needed properties to deployment
