%dev.quarkus.log.level=INFO

%test.quarkus.log.console.json.enabled=false
%test.quarkus.log.handler.kafka.enabled=false
quarkus.log.handler.kafka.broker-list=kafka.example.com:443
quarkus.log.handler.kafka.topic=kafka-topic
quarkus.log.handler.kafka.security-protocol=SSL
quarkus.log.handler.kafka.ssl-truststore-location=/mnt/kafka-client-truststore.jks
quarkus.log.handler.kafka.ssl-truststore-password=none
quarkus.log.handler.kafka.filter-logger-name-pattern=org.jboss.pnc.*
quarkus.log.handler.kafka.level=INFO

%test.quarkus.http.auth.basic=false
%test.quarkus.security.ldap.enabled=false
%test.quarkus.keycloak.devservices.enabled=false

%test.analyzer.pnc-url=https://orch-main-devel.pnc.engineering.redhat.com
%test.analyzer.koji-url=https://brewhub.engineering.redhat.com/brewhub
%test.analyzer.disable-cache=false
%test.analyzer.pnc-num-threads=1
%test.analyzer.disable-spdx-init=true

quarkus.infinispan-client.use-schema-registration=false
%dev.quarkus.infinispan-client.devservices.image-name=quay.io/infinispan/server:15.0.15.Final
%test.quarkus.infinispan-client.devservices.image-name=quay.io/infinispan/server:15.0.15.Final
